stages:         
  - test

matlab-test-job:   
  tags: 
    - matlab
  stage: test
  script:
    - matlab -batch "openProject('Convolution.prj'); results = runtests('IncludeSubfolders', true); disp(table(results)); assertSuccess(results);"
